### ISSUE TITLE
camelCase vs kebab-case

### ISSUE THREAD

**Issue by xave** [JonathanLorimer/htmx#6]
Is there any reason the instances for Render are in camelCase.

```
instance Render HtmxEvent where
    render = \case
        Abort -> "abort"
        ...
        AfterRequest -> "afterRequest"
```

I realize it's valid htmx, though I am getting a transformation (from the browser itself, it seems) that turns my html to all lowercase
```
hx-on::afterrequest="this.reset()"
            ^
```

My page initially loads everything just fine.
```
hx-on::afterRequest="this.reset()"
```

I have checked all the rendering functions I'm using Haskell side, and they seem to preserve the camelCase. Some browser event seems to be lowercasing everything. I'm testing on Safari, but this type of thing could happen on any browser at any time, I think.

It seems to me that it is safer to use the alternative *kebab-case* syntax. 

```
instance Render HtmxEvent where
    render = \case
        Abort -> "abort"
        ...
        AfterRequest -> "after-request"
```

**Comment by JonathanLorimer** [comment]
@xave Thank you for the issue, you seem to be absolutely right ([from the htmx docs](https://htmx.org/attributes/hx-on/)):
>One gotcha to note is that DOM attributes do not preserve case. This means, unfortunately, an attribute like hx-on:htmx:beforeRequest will not work, because the DOM lowercases the attribute names. Fortunately, htmx supports both camel case event names and also [kebab-case event names](https://htmx.org/docs/#events), so you can use hx-on:htmx:before-request instead.

I was originally following the [htmx event reference](https://htmx.org/reference/#events) which uses camel case, but it seems that kebab case is more appropriate.

I will try to have a change up tonight!

**Comment by JonathanLorimer** [comment]
@xave Live in [`htmx@0.1.0.1`](https://hackage.haskell.org/package/htmx-0.1.0.1/docs/src/Htmx.Event.html#local-6989586621679050088)
